MVCCoreTutorial/Models/ErrorViewModel.cs
using System;

namespace MVCCoreTutorial.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MVCCoreTutorial/Models/WebUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreTutorial.Models
{
	public class WebUser
	{

		[Required(ErrorMessage = "The First name is required.")]
		[StringLength(25, ErrorMessage = "The First name cannot be longer than 25 chars.")]
		[Display(Name = "First Name")]
		public string FirstName { get; set; }


		[Required(ErrorMessage = "The Last name is required.")]
		[StringLength(50, MinimumLength = 3, ErrorMessage = "The Last name cannot be longer than 50 chars.")]
		[Display(Name = "Last Name")]
		public string LastName { get; set; }


		public List<string> Countries { get; set; }



	}
}

MVCCoreTutorial/Models/Yolo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreTutorial.Models
{
	public class Yolo
	{	
		public int ID { get; set; }

		public string YoloMessage { get; set; }

	}
}

MVCCoreTutorial/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreTutorial.Controllers
{
	public class BlogController : Controller
	{
		[Route("blogs/")]
		public IActionResult Index()
		{
			return Content("blogs list here");
		}

		[Route("blogs/{entryId}/{slug}")]
		[Route("blog/{entryId}/{slug}")]
		public IActionResult Blog(int entryId, string slug)
		{
			return Content("Blog entry with ID " + entryId.ToString() + " requested (URL Slug: " + slug + ")");
		}
	}
}

MVCCoreTutorial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCCoreTutorial.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreTutorial.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MVCCoreTutorial/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreTutorial.Controllers
{
	public class ProductsController : Controller
	{
		public IActionResult Index(string ItemName)
		{
			//return View();
			return Content("This is the item: " + ItemName);
		}

	}
}

MVCCoreTutorial/Controllers/WebUserController.cs
using Microsoft.AspNetCore.Mvc;
using MVCCoreTutorial.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreTutorial.Controllers
{
	public class WebUserController : Controller
	{
		[HttpGet]
		public IActionResult Index()
		{
			WebUser wu = new WebUser();
			wu.FirstName = "";
			wu.LastName = "";
			wu.Countries = new List<string>()
												{
													"USA",
													"Great Britain",
													"Germany"
												};
			return View(wu);
		}

		[HttpPost]
		public IActionResult Index(WebUser wu)
		{
			if (ModelState.IsValid)
			{
				//Model state is valid
				return Json(wu);
			}
			else
			{
				//Model state is Invalid
				//return Content("Model state is invalid");
				return View(wu);
			}



		}

	}
}

MVCCoreTutorial/Controllers/YoloController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCCoreTutorial.Models;

namespace MVCCoreTutorial.Controllers
{
	public class YoloController : Controller
	{
		public IActionResult Index()
		{
			Yolo yolo = new Yolo();

			yolo.ID = 1;
			yolo.YoloMessage = "Yo only live oop";

			return View(yolo);
		}


		public IActionResult oop()
		{

			Yolo yolo = new Yolo();

			yolo.ID = 1;
			yolo.YoloMessage = "Yo only live oop";

			return Json(yolo);

		}
	}
}

MVCCoreTutorial/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCCoreTutorial/Views/Shared/_Greeting.cshtml
@{ 



}


<div class="container card">

    <div>Hello, world!</div>
    <div>Today is @DateTime.Now.ToString()</div>

    <span>
        Iteration number @ViewData["index"]
    </span>

</div>

MVCCoreTutorial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCoreTutorial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCoreTutorial</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yolo" asp-action="Index">Yolo View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yolo" asp-action="oop">Yolo JSON</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebUser" asp-action="Index">WebUser View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCCoreTutorial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCCoreTutorial/Views/Shared/_LoggedIn.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div>
    This si a partial view.
</div>

MVCCoreTutorial/Views/WebUser/Index.cshtml
@model MVCCoreTutorial.Models.WebUser

@{

}

@using (var form = Html.BeginForm())
{

    @Html.ValidationSummary()

    <div class="row">

        <div class="col">
            @Html.LabelFor(m => m.FirstName)
        </div>
        <div class="col">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", style = "font-weight: bold; font-size: 120%;" })

            <input asp-for="FirstName" class="form-control" style="font-weight: bold; font-size: 120%;" />

            @Html.ValidationMessageFor(m => m.FirstName)
        </div>

    </div>

    <div class="row">

        <div class="col">
            @Html.LabelFor(m => m.LastName)
        </div>
        <div class="col">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", style = "font-weight: bold; font-size: 120%;" })

            <input asp-for="LastName" class="form-control" style="font-weight: bold; font-size: 120%;" />

            @Html.ValidationMessageFor(m => m.LastName)
        </div>

    </div>



    <div class="row">

        <div class="col">
            label
        </div>
        <div class="col">
            <label asp-for="FirstName"></label>
        </div>

    </div>

    <div class="row">

        <div class="col">
            input
        </div>
        <div class="col">
            <input asp-for="FirstName" />
        </div>

    </div>

    <div class="row">

        <div class="col">
            textarea
        </div>
        <div class="col">
            <textarea asp-for="FirstName"></textarea>
            <textarea asp-for="FirstName" cols="25" rows="3"></textarea>
            <textarea asp-for="FirstName" style="height: 40px; width: 200px;"></textarea>
        </div>

    </div>

    <div class="row">

        <div class="col">
            select
        </div>
        <div class="col">

            <select class="form-control" asp-items="@(new SelectList(Model.Countries))" asp-for="Countries"></select>

        </div>

    </div>





    <div class="row">

        <div class="col">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

    </div>

}

MVCCoreTutorial/Views/Yolo/Index.cshtml
@model MVCCoreTutorial.Models.Yolo

@{
    ViewData["Title"] = "Yolo";

    var HtmlMessage = "<b>this is a messgae.</b>";

}

<div class="text-left">
    <h1 class="display-4">Yolo</h1>

    @Model.ID

    <br />

    @Model.YoloMessage

    <br />

    @HtmlMessage

    <br />

    @Html.Raw(HtmlMessage)

    <br />

    @(1 + 1)

    <br />

    @(HtmlMessage.Length )

    <br />

    @{
        var MultiMessage = "This is a multi message";

        <p>This is markup @MultiMessage</p>

    }

    <br />

    @MultiMessage

    <br />

    @{

        List<string> list = new List<string>();
        list.Add("Dave");
        list.Add("Mike");
        list.Add("Chuck");

    }

    <br />

    <ul>
        @for (int i = 0; i < list.Count; i++)
        {
            <li>@list[i]</li>
        }
    </ul>

    <ul>
        @foreach (string i in list)
        {
            <li>@i</li>
        }
    </ul>

    @{
        int k = 0;
    }

    <ul>
        @while (k < list.Count)
        {
            <li>@list[k++]</li>
        }
    </ul>

    @{
        int j = 0;
    }

    <ul>
        @do
        {
            <li>@list[j++]</li>
        } while (j < list.Count);
    </ul>

    <ul>
        @for (int l = 0; l < list.Count; l++)
        {
            <li>@list[l]</li>

            @if (l >= 2)
            {
                <li>...and so on</li>

                break;
            }
        }
    </ul>

    <br />

    @switch (DateTime.Now.DayOfWeek)
    {
        case DayOfWeek.Monday:
            <span>Uh-oh...</span>
            break;
        case DayOfWeek.Friday:
            <span>Weekend coming up!</span>
            break;
        case DayOfWeek.Saturday:
        case DayOfWeek.Sunday:
            <span>Finally weekend!</span>
            break;
        default:
            <span>Nothing special about this day...</span>
            break;
    }

    <br />
    @{
        void RenderTitleName()
        {
            <div>
                This is rendered from a function.
            </div>
        }

        int AnswerToLife(int x, int y)
        {
            return x * y;
        }
    }

    @{
        RenderTitleName();
    }

    <div>
        The answer to life: @AnswerToLife(7, 6)
    </div>
    <br />

    @{

        Func<dynamic, object> YoloTemplate = @<div>@item.ID: @item.YoloMessage</div>;

List<Yolo> yoloList = new List<Yolo>();

Yolo y = new Yolo();
y.ID = 12;
y.YoloMessage = "this is me";
yoloList.Add(y);

y = new Yolo();
y.ID = 42;
y.YoloMessage = "Another time";
yoloList.Add(y);

    }


    @foreach (Yolo yy in yoloList)
    {

        @YoloTemplate(yy);

    }

    <br />

    @await Html.PartialAsync("_Greeting")

    <br />

    @for (int i = 0; i < 3; i++)
    {

        <br />

        @await Html.PartialAsync("_Greeting", Model, new ViewDataDictionary(ViewData) { { "index", i } })

        <br />

    }

    <br />

    <br />

    <br />

    <br />

    <br />

    <br />

    <br />





</div>